language: java
jdk:
  - oraclejdk8
notifications:
  email:
  - email2vimalraj@gmail.com
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
